config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :subjects
  resources :courses
  resources :instructors
  root to: 'home#index'

  get 'search/index'
  get 'search/searchcourse' =>'search#searchcourse'
  get 'search/dosearchcourse' =>'search#dosearchcourse'
  post 'search/result' => 'search#result'
  get 'courses/:id/enroll(.:format)' => 'courses#enroll', as: 'enroll_course'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!
   def index
     @curr_user=current_user
     @subjects=Subject.order(:name)
  end
  def result
    if params[:search][:subject]==''
      @courses=Course.search(params[:search][:course]).order('name')
    else
     courses1=Subject.find(params[:search][:subject]).courses
     @courses=courses1.search(params[:search][:course]).order('name')
    end
  end
  
  def searchcourse
    @curr_user=current_user
    @subjects=Subject.order(:name)
  end
  def dosearchcourse
     if params[:subject]==''
      @courses=Course.search(params[:course]).order('name')
    else
     courses1=Subject.find(params[:subject]).courses
     @courses=courses1.search(params[:course]).order('name')
    end
    respond_to do |format|
      format.js
    end
  end
  def is_enrolled(course_id)
    if current_user.courses.include?(Course.find(course_id))
      return true
    else
      return false
    end
  end
  helper_method :is_enrolled
end

app/views/search/_search_results.html.erb
<h1>Search Result</h1>
<%if @courses.size==0%>
<p>No result found</p>
<%else%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Code</th>
      <th>Credits</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.code %></td>
        <td><%= course.credits %></td>
        <%if is_enrolled(course.id)%>
        <td>Enrolled</td>
        <%else%>
        <td><%= link_to 'Enroll', enroll_course_path(course) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<%end%>
<br>

app/views/search/dosearchcourse.js.erb
$('#search_results').html("<%= escape_javascript (render(partial: 'search_results')) %>");

app/views/search/index.html.erb
<form class="form-horizontal" method="post" action="result">
	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<fieldset>

<!-- Form Name -->
<legend>Search Course</legend>

<!-- Select Basic -->
<div class="form-group">
 
  <div class="col-md-4">
  	<label class="col-md-0 control-label" for="selectbasic">Subject</label>
   <%=select_tag 'search[subject]', options_from_collection_for_select(@subjects, 'id', 'name_and_id'),prompt: "Select Subject..."%>
  </div>
</div>
<div class="form-group">
 <!-- Text input-->
<div class="col-md-4">
  	<label class="col-md-0 control-label" for="textinput">Course</label>
  <input id="search_course" name="search[course]" placeholder="Type a course name..." class="form-control input-md" type="text">
  </div>
  </div>
  <div class="form-group">
  	 <div class="col-md-4">  	
    <input type="submit" id="singlebutton" name="singlebutton" value="Search" class="btn btn-primary">
  </div>
  	</div>
</fieldset>
</form>

app/views/search/result.html.erb
<p id="notice"><%= notice %></p>
	<%= link_to 'Change Search Criteria', search_index_path %>
	<h1>Search Result</h1>
<%if @courses.size==0%>
<p>No result found</p>
<%else%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Code</th>
      <th>Credits</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.code %></td>
        <td><%= course.credits %></td>
        <%if is_enrolled(course.id)%>
        <td>Enrolled</td>
        <%else%>
        <td><%= link_to 'Enroll', enroll_course_path(course) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<%end%>
<br>

app/views/search/searchcourse.html.erb
<div class="row">
<%= form_tag(search_dosearchcourse_path, method: "get", remote: true, role: "form", class: "form", id: "searchform" ) do %>
<div class"row">
	<div class="col-sm-5">
		<div class="form-group">
			<label class="control-label">Subject</label>
			<%= select_tag :subject, options_from_collection_for_select(@subjects, 'id', 'name_and_id'),prompt: "Select Subject...",:class=>"form-control"%>
		</div>
	</div>
	<div class="col-sm-5">
		<div class="form-group">
			<label class="control-label">Course</label>
			<%= text_field_tag(:course,"", class: "form-control",:placeholder=>"Type a course name...") %>
		</div>
	</div>
	
</div>
<% end %>
</div>
<div class="row">
	<div id="search_results"></div>
</div>

<script>
$(function() {
   $(".form-control").change(function() {
     $("form").submit();
   });
 });
</script>