config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :subjects
  resources :courses
  resources :instructors
  root to: 'home#index'

  get 'search/index'
  get 'search/searchcourse' =>'search#searchcourse'
  get 'search/dosearchcourse' =>'search#dosearchcourse'
  post 'search/result' => 'search#result'
  get 'courses/:id/enroll(.:format)' => 'courses#enroll', as: 'enroll_course'

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :enrollments
  has_many :users, through: :enrollments
  has_and_belongs_to_many :subjects
  self.primary_key = 'id'
  def self.search(name)
    where("name like ?", "%#{name}%") 
  end
end

app/models/courses_subject.rb
class Courses_subject < ActiveRecord::Base
  belongs_to :course
  belongs_to :subject
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  self.primary_key = 'id'
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_and_belongs_to_many :courses
  self.primary_key = 'id'
  def name_and_id
    name+'('+id+')'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :enrollments
  has_many :courses, through: :enrollments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << :firstname
  devise_parameter_sanitizer.for(:account_update) << :firstname
  
  devise_parameter_sanitizer.for(:sign_up) << :lastname
  devise_parameter_sanitizer.for(:account_update) << :lastname
end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy,:enroll]
  
  def enroll
    enrl=Enrollment.create(course_id: @course.id,user_id: current_user.id)
    enrl.save
    @notice='You are successfully enrolled in this course.'
  end

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :code, :credits, :continuity_id, :independent_study)
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def show
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]
   def index
     @curr_user=current_user
     @encourses=@curr_user.courses.order('name')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!
   def index
     @curr_user=current_user
     @subjects=Subject.order(:name)
  end
  def result
    if params[:search][:subject]==''
      @courses=Course.search(params[:search][:course]).order('name')
    else
     courses1=Subject.find(params[:search][:subject]).courses
     @courses=courses1.search(params[:search][:course]).order('name')
    end
  end
  
  def searchcourse
    @curr_user=current_user
    @subjects=Subject.order(:name)
  end
  def dosearchcourse
     if params[:subject]==''
      @courses=Course.search(params[:course]).order('name')
    else
     courses1=Subject.find(params[:subject]).courses
     @courses=courses1.search(params[:course]).order('name')
    end
    respond_to do |format|
      format.js
    end
  end
  def is_enrolled(course_id)
    if current_user.courses.include?(Course.find(course_id))
      return true
    else
      return false
    end
  end
  helper_method :is_enrolled
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :abbreviation, :comment)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseCatalog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Course Catalog', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
    	<% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
         <li><%= link_to 'Instructors', instructors_path %></li>
          <li><%= link_to 'Courses', courses_path %></li>
          <li><%= link_to 'Subjects', subjects_path %></li>
          <li><%= link_to 'Search', search_searchcourse_path %></li>
      </ul>
      <%end%>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.firstname %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">
    <h1><%= yield :header %></h1>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <p>Register to get started.</p>
      <p>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
      </p>
    </div>
  </div>
<% end %>